### 异常

当程序抛出异常时，有时程序员并不知道怎么处理，但可以停下来看看是否有其他人可以处理，把问题提交到一个高级的环境中，在那里做出更加正确的决定。

另外，异常处理可以降低代码处理错误的复杂度——不必针对每个特定的错误进行检查和解决，也不用在方法调用处检查，因为异常机制能够捕捉到错误。

异常阻止当前方法或者作用域继续执行程序，和普通错误还是有所区别。对于普通错误而言，当前环境下得到足够信息，就可以处理这个错误。而异常无法获得必要信息，要从当前的环境中跳出来，把问题交给上一级环境。

eg:除法时遇到除数为0，但是除数为0代表什么呢？有时你不能确认这个信息。如果0是上一个计算得到的，那是否是上一个计算出错？应当检查上一步计算。而又或者0是键盘键入的结果，如果是键盘键入，应当提醒输入者重新输入0.面对不同的问题情景，可能有不同的答案。

* try用来捕获异常，在里面放可能产生异常的调用
* catch用来处理不同的异常类型，每个catch有些仅有一种接收的异常。
* 异常处理有两种模型，**终止模型**和**恢复模型**，java采用终止模型，程序不再返回发生异常的地方重新执行了。如果想重新执行发生异常的语句，可以用while搭配try来使用
* 自定义异常：继承自最近的自己的Exception类，但是通常不好找，可以用**printStackTrace()**打印**调用序列**。默认输出在System.err。可以使用`printStackTrace(System.out)`输出在System.out

* 异常还可以写入日志

  ```java
  import java.util.*;
  import java.io.*;
  import java.util.logging.Logger;
  
  public class LoggingException {
      public static void main(String[] args) {
          try {
              throw new LogException();
          }catch (LogException e){
              System.err.println("Caught " + e);
          }
  
      }
  }
  
  class LogException extends Exception{
      // 创建了一个和LogException关联的Logger对象，会把输出发送给System.err
      private static Logger logger = Logger.getLogger("LogException");
      public LogException(){
          StringWriter trace = new StringWriter();
          // printStackTrace不会默认的产生字符串
          // 用stringWriter和PrintWriter来产生字符串
          printStackTrace(new PrintWriter(trace));
          logger.severe(trace.toString());
      }
  }
  ```

  

自定义异常中也可以加一些字段，建立自己的构造方法，还可以覆盖Throwable的getMessage()方法

* 栈的轨迹调用：printStackTrace()里的调用信息可以用getStackTrace()调用，会返回一个由栈的轨迹元素所构成的数组。栈顶是最后一个调用（0），即抛出异常的调用，栈底是第一条调用。可以使用foreach

  ```java
  for(StackTraceElement ste : e.getStackTrace()){
      System.out.println(ste.getMethodName());
  }
  ```

* 重新抛出异常：可以在catch语句直接throw e;同一个try块后面的catch会被全部忽略。此时调用fillStackTrace()可以获得新的抛出点的信息。



#### Java标准异常

Throwable可以表示Java中任何可以作为异常被抛出的类，分为Error和Exception。Error表示编译时or系统错误，不需要程序员主动来关心。Exception才是经常要处理的异常，但是这里有个特例就是RuntimeException.它属于错误，会被直接捕获。因为它代表了编程错误：

* 无法预测的错误：比如传来了null对象
* 应在代码中检查的错误：比如数组越界

![img](https://images2015.cnblogs.com/blog/844237/201602/844237-20160219182128206-1953842539.png)

checked： 一般是指程序不能直接控制的外界情况，是指在编译的时候就需要检查的一类exception，用户程序中必须采用try catch机制处理或者通过throws交由调用者来处理。这类异常，主要指除了Error以及RuntimeException及其子类之外的异常。

unchecked：是指那些不需要在编译的时候就要处理的一类异常。在java体系里，所有的Error以及RuntimeException及其子类都是unchecked异常。再形象直白的理解为不需要try catch等机制处理的异常，可以认为是unchecked的异常。



#### Finally

finally是最后一定会执行的部分，无论异常是否抛出。它不管遇到return 还break还是continue都会执行。

但有时会引起**异常缺失**问题。

```java
try{
    //
    try{
        throw new A();
    }finally{
        throw new B()
    }
}catch(Exception e){
    //
}
```

在上段代码中只会catch到B异常，而不会catch到A，B把A取代了

还有种情况是

```java
try{
    //
    
}finally{
    return;
}
```

即使遇到异常，也不会有异常抛出